/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.freixas.jcalendar.JCalendarCombo;
/**
 *
 * @author resa
 */
public class FrmPelanggan extends javax.swing.JInternalFrame {

    DefaultTableModel tabelModel;
    /**
     * Creates new form FrmPelanggan
     */
    public FrmPelanggan() {
        initComponents();
        tabelModel = new DefaultTableModel();
        tabel.setModel(tabelModel);
        
        tabelModel.addColumn("ID");
        tabelModel.addColumn("Nama");
        tabelModel.addColumn("Alamat");
        tabelModel.addColumn("Telp");
        tabelModel.addColumn("Gender");
        tabelModel.addColumn("TglLahir");
        tabelModel.addColumn("Usia");
        
       
        calendar.setDateFormat(new SimpleDateFormat("yyyy-MM-dd")); //yyyy-MM-dd
        autoNumber();
        tampilTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlamat1 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        panel = new ClPanelTransparant();
        jLabel2 = new javax.swing.JLabel();
        lblNama1 = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblTelp = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblTglLahir = new javax.swing.JLabel();
        lblUsia = new javax.swing.JLabel();
        txtUsia = new javax.swing.JTextField();
        calendar = new org.freixas.jcalendar.JCalendarCombo(JCalendarCombo.DISPLAY_DATE,false);
        cbGender = new javax.swing.JComboBox();
        txtTelp = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        lblIcon = new javax.swing.JLabel();
        lblWall = new javax.swing.JLabel();

        lblAlamat1.setText("Alamat : ");

        setClosable(true);
        setIconifiable(true);
        setTitle("Form Pelanggan");
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollPaneMouseClicked(evt);
            }
        });

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(tabel);

        getContentPane().add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 660, 220));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 120, 40));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/simpan.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 140, 40));

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/ubah.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        getContentPane().add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 110, 40));

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pelanggan", 0, 0, new java.awt.Font("Comic Sans MS", 1, 10), new java.awt.Color(255, 204, 255))); // NOI18N
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID Pelanggan : ");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblNama1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblNama1.setForeground(new java.awt.Color(255, 255, 255));
        lblNama1.setText("Nama : ");
        panel.add(lblNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        lblAlamat.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblAlamat.setForeground(new java.awt.Color(255, 255, 255));
        lblAlamat.setText("Alamat : ");
        panel.add(lblAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblTelp.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTelp.setForeground(new java.awt.Color(255, 255, 255));
        lblTelp.setText("Telp : ");
        panel.add(lblTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblGender.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender : ");
        panel.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblTglLahir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblTglLahir.setForeground(new java.awt.Color(255, 255, 255));
        lblTglLahir.setText("Tgl Lahir : ");
        panel.add(lblTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lblUsia.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblUsia.setForeground(new java.awt.Color(255, 255, 255));
        lblUsia.setText("Usia : ");
        panel.add(lblUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        panel.add(txtUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 90, -1));
        panel.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pria", "Wanita" }));
        panel.add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 170, -1));
        panel.add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 180, -1));
        panel.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 350, -1));
        panel.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 290, -1));

        txtID.setEditable(false);
        panel.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 180, -1));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 610, 310));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/refresh.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 120, 40));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/pelanggan.png"))); // NOI18N
        getContentPane().add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 160, 170));

        lblWall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan/wall.jpg"))); // NOI18N
        getContentPane().add(lblWall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 890, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
         String gender = "";
        if(cbGender.getSelectedIndex() == 0)
        {
            gender = "Pria";
        }
        else if(cbGender.getSelectedIndex() == 1)
        {
            gender = "Wanita";
        }
         try
        {
        Connection konek = Koneksi.getKoneksi();
        String query = "UPDATE pelanggan SET Nama = ?, Alamat = ?, NoTelp = ?, Gender = ?, TglLahir = ?, Usia = ? WHERE ID = ?";
        PreparedStatement prepare = konek.prepareStatement(query);
       
        prepare.setString(1, txtNama.getText());
        prepare.setString(2, txtAlamat.getText());
        prepare.setString(3, txtTelp.getText());
        prepare.setString(4, gender);
        prepare.setString(5, (String) calendar.getSelectedItem());
        prepare.setInt(6, Integer.parseInt(txtUsia.getText()));
        prepare.setString(7, txtID.getText());
        
        prepare.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil diubah");
        prepare.close();
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data gagal diubah");
            System.out.println(ex);
        }
        finally
        {
            tampilTabel();
        }
        
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String gender = "";
        if(cbGender.getSelectedIndex() == 0)
        {
            gender = "Pria";
        }
        else if(cbGender.getSelectedIndex() == 1)
        {
            gender = "Wanita";
        }
        try
        {
        Connection konek = Koneksi.getKoneksi();
        String query = "INSERT INTO pelanggan VALUES(?,?,?,?,?,?,?)";
        PreparedStatement prepare = konek.prepareStatement(query);
        
        prepare.setString(1, txtID.getText());
        prepare.setString(2, txtNama.getText());
        prepare.setString(3, txtAlamat.getText());
        prepare.setString(4, txtTelp.getText());
        prepare.setString(5, gender);
        prepare.setString(6, (String) calendar.getSelectedItem());
        prepare.setInt(7, Integer.parseInt(txtUsia.getText()));
        
        prepare.executeUpdate();
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        prepare.close();
        }
        
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            System.out.println(ex);
        }
        finally
        {
            autoNumber();
            tampilTabel();
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void scrollPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollPaneMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_scrollPaneMouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        int a = tabel.getSelectedRow();
        
        if(a == -1)
        {
            return;
        }
        
        String id = (String) tabelModel.getValueAt(a, 0);
        txtID.setText(id);
        String nama = (String) tabelModel.getValueAt(a, 1);
        txtNama.setText(nama);
        String alamat = (String) tabelModel.getValueAt(a, 2);
        txtAlamat.setText(alamat);
        String telp = (String) tabelModel.getValueAt(a, 3);
        txtTelp.setText(telp);
        String gender = (String) tabelModel.getValueAt(a, 4);
        cbGender.setSelectedItem(gender);
        String tglLahir = (String) tabelModel.getValueAt(a, 5);
        calendar.setSelectedItem(tglLahir);
        int usia = (int) tabelModel.getValueAt(a, 6);
        txtUsia.setText("" + usia);
        
    }//GEN-LAST:event_tabelMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection konek = Koneksi.getKoneksi();
            String query = "DELETE FROM pelanggan WHERE ID = ?";
            PreparedStatement prepare = konek.prepareStatement(query);
            
            prepare.setString(1, txtID.getText());
            prepare.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
            prepare.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "Data gagal dihapus");
            System.out.println(ex);
        }
        finally
        {
            tampilTabel();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        refresh();
        autoNumber();
    }//GEN-LAST:event_btnRefreshActionPerformed
                                  
    
    public void tampilTabel()
    {
        tabelModel.getDataVector().removeAllElements();
	tabelModel.fireTableDataChanged();
        try
        {
            Connection konek = Koneksi.getKoneksi();
            Statement state = konek.createStatement();
            String query = "SELECT * FROM pelanggan";
            
            ResultSet rs = state.executeQuery(query);
            
            while(rs.next())
            {
                Object obj[] = new Object[7];
                obj[0] = rs.getString(1);
                obj[1] = rs.getString(2);
                obj[2] = rs.getString(3);
                obj[3] = rs.getString(4);
                obj[4] = rs.getString(5);
                obj[5] = rs.getString(6);
                obj[6] = rs.getInt(7);
                
                tabelModel.addRow(obj);
            }
        }
        catch(Exception ex)
        {
            System.out.println(ex);
        }
    }
    
    private class ClPanelTransparant extends JPanel
{
	private Color clr;
	
	public ClPanelTransparant()
	{
		setOpaque(false);
		clr = new Color(getBackground().getRed(), getBackground().getRed(), getBackground().getGreen(),50);
	}	
	
	public void setBackground(Color bg)
	{
		super.setBackground(bg);
		clr = new Color(getBackground().getRed(), getBackground().getRed(), getBackground().getGreen(), 50);
		repaint();
	}
	
	protected void paintComponent(Graphics graph)
	{
		super.paintComponent(graph);
		Graphics2D g2d = (Graphics2D) graph.create();
		g2d.setColor(clr);
		g2d.fillRect(0, 0, getWidth(), getHeight());
		g2d.dispose();
	}
	
}
    
    public void autoNumber()
	{
		try
		{
			Connection konek = Koneksi.getKoneksi();
			Statement state = konek.createStatement();
			String query = "SELECT MAX(right(ID,2)) AS no FROM pelanggan";
			
			ResultSet rs = state.executeQuery(query);
			while(rs.next())
			{
				if(rs.first() == false)
				{
					txtID.setText("P001");
				}
				else
				{
					rs.last();
					int noID = rs.getInt(1) + 1;
					String no = String.valueOf(noID);
					int noLong = no.length();
					for(int a=0;a<2-noLong;a++)
					{
						no = "00" + no;
					}
					txtID.setText("P" + no);
				}
					
			}
			rs.close();
			state.close();
		}
		catch(Exception ex)
		{
			System.out.println(ex);
		}
	}
    
    public void refresh()
    {
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelp.setText("");
        cbGender.setSelectedIndex(0);
        txtUsia.setText("");
        txtNama.requestFocus();
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private org.freixas.jcalendar.JCalendarCombo calendar;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblAlamat1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblNama1;
    private javax.swing.JLabel lblTelp;
    private javax.swing.JLabel lblTglLahir;
    private javax.swing.JLabel lblUsia;
    private javax.swing.JLabel lblWall;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtUsia;
    // End of variables declaration//GEN-END:variables
}
